name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "*/60 * * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install psl publicsuffix whois
      - run: git config user.name github-actions
      - run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: ./update.sh | tee /tmp/commit-message
      - run: ./avail.sh | tee -a /tmp/commit-message
      - run: if git commit -a -F /tmp/commit-message; then git push; fi
